# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f18feb0f947beb357e5c0d995c7bda02e787f8359f9dc2eb89f478f32a20d27c76880ec64c9b38a5750cf142713de16b8eb6389fbc6db9f95a6537eb1df324f

test:
  secret_key_base: 5bab575343f862a42e4fb71419d2b1280e1541a0d85dc9a6eefaa974d9d5fc5d53d6eb8be293e21799d3532d4b5e782cd42f2f36ab90ba11d21ec91a6736ce0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
